### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fable.Elmish.Bulma#14]
- [x] Panel
- [x] Modal
- [x] Nav
- [x] Pagination
- [x] Tabs
- [x] Grid
- [ ] Form
  - [ ] Input
  - [ ] Control
  - [ ] Field
  - [ ] etc.
- [x] Notification
- [x] Home page
- [x] Why Elmish.Bulma ?
- [x] How to use it ?

**Comment by kunjee17** [comment]
I guess input doc is also missing. Or may be missed to linked.

**Comment by MangelMaxime** [comment]
Input will be added to Form. Like textarea, control, field, etc.
