### ISSUE TITLE
Maybe default to title class on h1 etc?

### ISSUE THREAD

**Issue by bentayloruk** [MangelMaxime/Fable.Elmish.Bulma#18]
If I write:

`Heading.h1 [] [ str "Awesome title"]`

I get the following, which does not get styled:

`<h1 class=" is-1">Awesome title</h1>`

But I was expecting:

`<h1 class="title is-1">Awesome title</h1>`

I see the `Heading.isTitle` option works, but I'm thinking it might be nice to default to `title` if the option is missing?

**Comment by MangelMaxime** [comment]
That's a good point.

**Comment by MangelMaxime** [comment]
Published in alpha6
