### ISSUE TITLE
Wrong capitalization in icon docs

### ISSUE THREAD

**Issue by rmunn** [MangelMaxime/Fable.Elmish.Bulma#26]
I just noticed that the https://mangelmaxime.github.io/Fable.Elmish.Bulma/#elements/icon code sample for the `faIcon` function has a typo in it, caused by my typing that code sample into the comment box in a hurry. The actual function is `faIcon` (starting wtih a lowercase letter), but my code sample which you copied used `FaIcon`. So now the sample code on the docs page is wrong: it should be `faIcon`, not `FaIcon`.

Also, there's an inconsistency in the docs about the `Fa.Custom` capitalization: the sample code correctly uses `Custom` (capital letter), but the line in the docs just before it incorrectly says "You can also use `Fa.custom "fa-my-icon"` as a fix." That lie should be `Fa.Custom` as well.

Finally, the line that reads "We provide convenience functions for **font awesome**" should really be written as "We provide convenience functions for **Font Awesome**" since the Font Awesome project's official name is capitalized like that.

**Comment by MangelMaxime** [comment]
Thanks for the report. 👍 

Can you please check if I didn't miss one of typo [here](https://mangelmaxime.github.io/Fable.Elmish.Bulma/#elements/icon) ?

**Comment by rmunn** [comment]
Looks good!
