### ISSUE TITLE
Be more Bulma and less Elmish :p

### ISSUE THREAD

**Issue by evilz** [MangelMaxime/Fable.Elmish.Bulma#32]
May be take inspriration from real bulma site ? 
The actual header is not sexy, and it miss a logo !

All great projects start with a great logo ;)

Buefy can be source of inspration https://buefy.github.io

Current menu is nice and simple, but if we add some stuff it will not scale.

It miss may be a full api section ?

**Comment by MangelMaxime** [comment]
I agree the actual site need some design work and I am already working on it to include the next major evolution of this repo.

This work include:
- Small refactoring on the header
- Make the menu dynamic

In a near future, I would also like to include a good API section as this will make sense for one of the new evolutions.

To conclude, I also agree on the logo and this would be needed after the current rework to help give an identity to the project/libs.

After, the current rework I am not against new layout propositions but I would like this website not to be clone of [bulma.io](http://bulma.io). The idea being to show another way to use Bulma. Most of the bulma's docs sites looks the same and I find it sad for such a powerful framework.

**Comment by evilz** [comment]
Looks good 👍 
Maybe a more simple name that Fable.Elmish.Bulma can be simple to remind and talk about.
I was thinking about something like   "Fulma" using the F logo of fable.

![](https://farm5.staticflickr.com/4382/36051807323_89ca34e8a9_b.jpg)

**Comment by MangelMaxime** [comment]
I like the idea.

@alfonsogarciacaro I quite like the idea of using `Fulma.React` name instead of our lastest idea `Fable.React.Bulma` ?

So we would have:

- `Fulma.React` -> wrapper over bulma
- `Fulma.Extensions.React` -> wrapper over bulma extensions
- `Fulma.Components.React` -> reusable components datetime picker, sortable table

**Comment by evilz** [comment]
Cool, it's look simple but don't you think Component term can be confusing with Bulma components ?
Sorry I don't think of a good term to replqce it.  may be `Behaviors` or `Extra` ?

**Comment by MangelMaxime** [comment]
You are right there collision between the namespaces.

So I propose `Fulma.Elmish` as these "components" are design for Elmish architecture.

**Comment by MangelMaxime** [comment]
Ok, I made Fulma's logo by editing Fable.svg logo.

Here are the current versions:

Mini logo:
![mini_logo 1](https://user-images.githubusercontent.com/4760796/29769463-c63bab2a-8bea-11e7-9b99-abb5eb4beec7.png)

Logo with background:
![logo](https://user-images.githubusercontent.com/4760796/29769467-c90764fc-8bea-11e7-99f5-64383816bead.png)

Transparent version:
![logo_transparent](https://user-images.githubusercontent.com/4760796/29769466-c8d73c78-8bea-11e7-992b-432f53a0e21f.png)

Here is the zip with the svg files: 
[logos_svg.zip](https://github.com/MangelMaxime/Fable.Elmish.Bulma/files/1256470/logos_svg.zip)

**Comment by evilz** [comment]
So nice :+1:

**Comment by kunjee17** [comment]
All good with name and all but please don't change the URL. :P 

Just kidding I am very much in support  of suggestion.

**Comment by MangelMaxime** [comment]
I am closing as it's already ready in master branch
