### ISSUE TITLE
React and react-dom not found

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fable.Elmish.Bulma#35]
@alfonsogarciacaro with your PR and little changes to the `fsproj` I have been able to build Fulma for netstandard1.6 even by using a netstandard2.0 format. 🎉 👏 

However, I am facing an issue when trying to build the docs site.
Rollup can't find `react` and `react-dom`

Extract from the build logs:
```
fable: Compiled ..\..\..\..\..\.nuget\packages\fable.elmish.react\0.9.0\fable\react.fs
⚠️   'react-dom' is imported by ..\..\..\..\..\.nuget\packages\fable.elmish.react\0.9.0\fable\react.fs, but could not be resolved – treating it as an external dependency
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency

fable: Compiled ..\..\..\..\..\.nuget\packages\fable.elmish.react\0.9.0\fable\common.fs
⚠️   'react' is imported by ..\..\..\..\..\.nuget\packages\fable.elmish.react\0.9.0\fable\common.fs, but could not be resolved – treating it as an external dependency
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
```

In the docs.fsproj I also need to change this lines:

```xml
  <ItemGroup>
    <ProjectReference Include="../src/Fulma/Fulma.fsproj" />
    <ProjectReference Include="../src/Fulma.Extensions/Fulma.Extensions.fsproj" />
  </ItemGroup>
```

by

```xml
  <ItemGroup>
    <ProjectReference Include="../src/Fulma.Extensions/Fulma.Extensions.fsproj" />
  </ItemGroup>
```

which seems wrong. Latest version of the project is on branch *feature/conversion* if you can take a look at this problem this would be nice. :) I believe other people could face it too.

I could still include react as an external dependency but managing the deps version would become harder etc.

**Comment by MangelMaxime** [comment]
If ever it's easier for you, we can replace rollup with webpack as it as better support for the `.sass` file. And If I remember well passing babelOption to webpack is easier. It's up to know.

Rollup only listen the change on the `main.sass` file where webpack can listen all the files includes by `main.sass`.

I am also offering this choice because at the beginning I choose rollup because it was easier to configure and debug but since a little while it's no more the case with the limitation of some of his plugins.

**Comment by alfonsogarciacaro** [comment]
Rollup is a bit of a pain when the project structure gets a bit complicated but anyways I had the same problem with `react` and it should be fixed by [adding this to the config](https://github.com/MangelMaxime/Fable.Elmish.Bulma/pull/34/files#diff-2b61307e674b52fad1853c998b991ee3R43), isn't it working for you?

```js
nodeResolve({
    customResolveOptions: {
        moduleDirectory: path.join(__dirname, '../node_modules')
    }
}),
```

I'll also have a look about the project references :+1:

**Comment by alfonsogarciacaro** [comment]
I have the problem with the project references but not with Fable, it's when I run `dotnet restore` that I get:

```
/usr/local/share/dotnet/sdk/2.0.0/NuGet.targets(102,5): error : An item with the same key has already been added. Key: (Fulma, 0.2.0-beta-002) [/Users/alfonsogarciacaronunez/dev/Fulma/docs/docs.fsproj]
```

I have to remove the Fulma.fsproj reference and leave only Fulma.Extensions.fsproj (as you did above ☝️) to fix it.

BTW, I cannot bundle latest feature/conversion branch because I get this error:

```
Error: File to import not found or unreadable: ./../../src/Fulma.Extensions/styles/bulma-calendar/calendar.sass.
Parent style sheet: /Users/alfonsogarciacaronunez/dev/Fulma/docs/sass/main.sass
sass/main.sass
```

**Comment by MangelMaxime** [comment]
For the bundle error it's because, I am using `git submodule` to include Bulma's extensions references.

You need to run
```
git submodule init
git submodule update (this one is probably optional)
```

I will try to investigate the `dotnet restore` issue, it's probably something related to paket and the storage feature.

**Comment by MangelMaxime** [comment]
And for the react problem I am still having it, `moduleDirectory` seem to not be enough.

**Comment by MangelMaxime** [comment]
Ok for info, I reference our issue with the `restore` target here https://github.com/fsprojects/Paket/issues/2695

**Comment by evilz** [comment]
I think @alfonsogarciacaro is right.  

I remove the reference to Fulma nuget in Fulma.Extensions project.
If it was there to create the package, I think it must use the packet.template file.

I also fix the submodule. But I really don't like it since I don't use ssl key manager. I'mworking over https ...

Then I got a new error:

```sh
bundling...
Parsing ./docs.fsproj...
fable: Compiled docs.fsproj
fable: Compiled src\App.fs
⚠   (fable plugin) D:/Fable.Elmish.Bulma/docs/src/Fulma/Dispatcher/View.fs(10,14): (10,21) warning FSHARP: Incomplete pattern matches on th
is expression. For example, the value 'Form' may indicate a case not covered by the pattern(s).
src\Fulma\Dispatcher\View.fs

fable: Compiled src\Fulma\Dispatcher\View.fs
fable: Compiled src\Fulma\Components\Level\View.fs
fable: Compiled ..\src\Fulma\Components\Level.fs
🚨   Error: Could not resolve './C:/Users/vbourdon/.nuget/packages/fable.core/1.2.0-beta-002/fable-core/Symbol' from ..\src\Fulma\Components
\Level.fs
```

**Comment by MangelMaxime** [comment]
I didn't know about `paket.template` will take a look at it.

For the submodules problem, I will explore another way to include reference over the extensions libs.

**Comment by MangelMaxime** [comment]
@evilz The reference problems will be fixed in the next beta version of Fable. So the strange line should not occur again hopefully :)

**Comment by alfonsogarciacaro** [comment]
@evilz I've released dotnet-fable 1.2.0-beta-005, could you please try again? I couldn't test because I'm on macOS, but hopefully this solves the problem of paths with different drive letters on Windows.

**Comment by MangelMaxime** [comment]
Just to keep tracks of the actions.

We are moving to webpack in this PR: https://github.com/MangelMaxime/Fable.Elmish.Bulma/pull/36

Rollup is causing problems for sass files watch and also to import react.

**Comment by evilz** [comment]
@MangelMaxime @alfonsogarciacaro It now working like a charm ! 
Webpack + dotnet-fable (1.2.0-beta-005)

GG guys !

**Comment by MangelMaxime** [comment]
I am closing this issue as it solve in the dev branch
